import random

def tightCheck(string):
    for i in range(1, int(len(string)/2)+1):
        j = 0
        while j+i+i <= len(string): 
            '''
            try:
                print('--'+string[j:j+i])
                print('++'+string[j+i:j+i+i])
            except:
                pass 
                '''
            if string[j:j+i] == string[j+i:j+i+i]: 
                print('False')
                print(j)
                print('reaper' + string[j:j+i]) 
                return False
            j += 1
    return True


def generateRandom(symbols=['A', 'B', 'C']):
    randStr = ''
    for i in range(random.randint(40, 100)):
        curr = random.choice(symbols)
        randStr += curr
        symbols = ['A', 'B', 'C']
        symbols.remove(curr)
    return randStr
'''
for j in range(50):
    rand = generateRandom()
    print(rand)
    tightCheck(rand)
'''
#tightCheck('ABACABCACBACABCA')

#tightCheck('ABACBABCBACBCABACBABCBACABACBABCABACBCABCBABCABACBABCBACBCABACBABCABACBCABCBABCABACBABCBACABACBABCABACBCABCBABCABACBABCACBACABACBABCBACBCABACBABCBACABACBABCABACBCABCBABCABACBABCBACBCABACBABCABACBCABCBABCABACBABCBACABACBABCABACBCABCBABCABACBABCACBCABACBABCBACBCABACBABCABACBCABCBABCABACBABCBACBCABACBABCABACBCACBABCBACBCABACBABCBACBCACBABCBACABACBABCBACBCABACBABCBACABACBABCABACBCABCBABCABACBABCBACBCABACBABCABACBCABCBABCABACBABCBACABACBABCABACBCABCBABCABACBABCACBACABACBABCBACBCABACBABCBACABACBABCABACBCABCBABCABACBABCBACBCABACBABCABACBCABCBABCABACBABCBACABACBABCABACBCABCBABCABACBCACBABCBACBCABACBABCBACBCACBABCBACABACBABCBACBCABACBABCBACABACBABCABACBCABCBABCABACBABCBACBCABACBABCABACBCABCBABCABACBABCBACABACBABCABACBCABCBABCABACBABCACBACABACBABCBACBCABACBABCBACABACBABCABACBCABCBABCABACBABCBACBCABACBABCABACBCABCBABCABACBABCBACABACBABCABACBCACBABCBACBCABACBABCBACBCACBABCBACABACBABCBACBCABACBABCBACABACBABCABACBCACBACABCACBCABCBACABCACBACABCBACBCACBACABCACBCABCBACABCACBACABACBCACBACABCACBCABCBACABCACBABCABACABCACBCABCBACABCACBCABACABCACBACABCBACBCACBACABCACBCABCBACABCACBACABCBACBCACBACABCACBCABACABCACBACABCBACBCACBACABCACBABCABACABCACBCABCBACABCACBCABACABCACBACABCBACBCACBACABCACBCABCBACABCACBACABCBACBCACBACABCACBCABACABCACBACABCBABCACBCABCBACABCACBCABCBABCACBCABACABCACBCABCBACABCACBCABACABCACBACABCBACBCACBACABCACBCABCBACABCACBACABCBACBCACBACABCACBCABACABCACBACABCBACBCACBACABCACBABCABACABCACBCABCBACABCACBCABACABCACBACABCBACBCACBACABCACBCABCBACABCACBACABCBACBCACBACABCACBCABACABCACBACABCBACBCACBACABCBABCACBCABCBACABCACBCABCBABCACBCABACABCACBCABCBACABCACBCABACABCACBACABCBACBCACBACABCACBCABCBACABCACBACABCBACBCACBACABCACBCABACABCACBACABCBACBCACBACABCACBABCABACABCACBCABCBACABCACBCABACABCACBACABCBACBCACBACABCACBCABCBACABCACBACABCBACBCACBACABCACBCABACABCACBACABCBABCACBCABCBACABCACBCABCBABCACBCABACABCACBCABCBACABCACBCABACABCACBACABCBACBCACBACABCACBCABCBACABCACBACABCBACBCACBACABCACBCABACABCACBC')


tightCheck('ABACABCACABACABCBA')

