def check(string):
    n = len(string)
    last = string[-1]
    if n > 4:
        for i in range(-1, -(int(n/2)+2), -1):
            if i == -1:
                pass
            elif i == -2:
                if last != string[-2]:
                    pass
                else:
                    return false
            else:
                if last == string[i]: 
                    if string[i+1:-1] != string[i+(i+2):i]:
                        pass
                    else:
                        #print("repeat found")
                        #print(string)
                        #print(i)
                        #print(n+i)
                        #print(string[i+1:-1])
                        #print(string[i+(i+2):i])
                        return false
        return true
    else:
        return string[-1] != string[-2] and string[2:] != string[:2]


#myStr = 'ACBCACBACABCBACBCACBACABCACBCABCBACBCACBACABCBACBCABCBACABCACBCABCBACBCACBACABCBABCACBCABCBACBCACBACABCACBCABCBACBCACBABCBACBCABCBACABCACBCABCBACBCACBACABCBACBCABCBACABCACBCABCBACBCACBABCBACBCABCBACABCACBCABCBACBCABACBABCBACBCACBACABCBACBCACBABCBACBCABCBACABCACBCABCBACBCACBACABCBACBCABCBACABCACBCABCBACBCACBABCBACBCABCBACABCACBCABCBACBCABACBABCBACBCABCBACABCACBCABCBACBCACBACABCBACBCABCBACABCACBCABCBACBCACBABCBACBCABCBACABCACBCABCBACABACBCACBACABCBACBCACBACABACBCACBABCBACBCACBACABCBACBCACBABCBACBCABCBACABCACBCABCBACBCACBACABCBACBCABCBACABCACBCABCBACBCACBABCBACBCABCBACABCACBCABCBACBCABACBABCBACBCACBACABCBACBCACBABCBACBCABCBACABCACBCABCBACBCACBACABCBACBCABCBACABCACBCABCBACBCACBABCBACBCABCBACABCACBCABCBACABACBCACBACABCBACBCACBACABACBCACBABCBACBCACBACABCBACBCACBABCBACBCABCBACABCACBCABCBACBCACBACABCBACBCABCBACABCACBCABCBACBCACBABCBACBCABCBACABCACBCABCBACBCABACBABCBACBCACBACABCBABCACBCABCBACBCACBACABCBACBCABCBACABCACBCABCBACBCACBACABCBACBCABCBABCACBCABCBACBCACBACABCBACBCABACBC'

#for k in range(88,91):
#    print('SLIME')
#    print(myStr[:k])
#    print(check(myStr[:k]))
